___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

## 📌 What is a DataFrame in pandas?

A DataFrame is a two-dimensional labeled data structure in pandas.

You can think of it as:

📊 A table (like Excel sheet)

🗂 A collection of Series

📋 Rows and Columns with labels

👉 Each column in a DataFrame is a Series.

🔹 Structure of a DataFrame

It has:

``Rows (index)``

``Columns``

``Values``

### Example:
| Index | Name  | Marks | City      |
| ----- | ----- | ----- | --------- |
| 0     | Ali   | 85    | Karachi   |
| 1     | Sara  | 90    | Lahore    |
| 2     | Ahmed | 78    | Islamabad |

In [118]:
import pandas as pd
import numpy as np

In [119]:
from numpy.random import randn
np.random.seed(101)

## Creating Data Frame

In [120]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [121]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [122]:
data = {
    'Name': ['Ali', 'Sara', 'Ahmed'],
    'Marks': [85, 90, 78],
    'City': ['Karachi', 'Lahore', 'Islamabad']
}

df = pd.DataFrame(data)
df

    Name  Marks       City
0    Ali     85    Karachi
1   Sara     90     Lahore
2  Ahmed     78  Islamabad

In [123]:
df['Name']

0      Ali
1     Sara
2    Ahmed
Name: Name, dtype: object

In [124]:
df["New"] = df["Name"]+df["City"]
df

    Name  Marks       City             New
0    Ali     85    Karachi      AliKarachi
1   Sara     90     Lahore      SaraLahore
2  Ahmed     78  Islamabad  AhmedIslamabad

In [125]:
df.drop(columns="New",axis=1)

    Name  Marks       City
0    Ali     85    Karachi
1   Sara     90     Lahore
2  Ahmed     78  Islamabad

In [126]:
df.drop(labels=1,axis=0)

    Name  Marks       City             New
0    Ali     85    Karachi      AliKarachi
2  Ahmed     78  Islamabad  AhmedIslamabad

In [127]:
df

    Name  Marks       City             New
0    Ali     85    Karachi      AliKarachi
1   Sara     90     Lahore      SaraLahore
2  Ahmed     78  Islamabad  AhmedIslamabad

In [128]:
df.drop(labels=1,axis=0,inplace=True)
df

    Name  Marks       City             New
0    Ali     85    Karachi      AliKarachi
2  Ahmed     78  Islamabad  AhmedIslamabad

## Selecting Rows

In [129]:
df.loc[0]

Name            Ali
Marks            85
City        Karachi
New      AliKarachi
Name: 0, dtype: object

In [130]:
df.iloc[1]

Name              Ahmed
Marks                78
City          Islamabad
New      AhmedIslamabad
Name: 2, dtype: object

In [131]:
df[['City','Name']]

        City   Name
0    Karachi    Ali
2  Islamabad  Ahmed

In [132]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [133]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [134]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [135]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

DataFrame Columns are just Series

In [136]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [137]:
df['new'] = df['W'] + df['Y']

In [138]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

** Removing Columns**

In [139]:
df.drop('new',axis=1)

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [140]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [141]:
df.drop('new',axis=1,inplace=True)

In [142]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

Can also drop rows this way:

In [143]:
df.drop('E',axis=0)

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

## Selecting Rows

In [144]:
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

Or select based off of position instead of label

In [145]:
df.iloc[2]

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

## Selecting subset of rows and columns

In [146]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [147]:
df.loc[["B","C"]]

          W         X         Y         Z
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646

In [148]:
df.loc["B","Z"]

np.float64(0.18450185928224264)

In [149]:
df.loc[["D","E"],["Y","Z"]]

          Y         Z
D -0.943406  0.484752
E  0.238127  1.996652

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [150]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [151]:
df>0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [152]:
df[df>0]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [153]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [154]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [155]:
df[df['W']>0]['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [156]:
df[df['W']>0][['Y','X']]

          Y         X
A -1.706086  1.693723
C  0.638787  0.072960

In [157]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [158]:
df['Y'] > 1

A    False
B    False
C    False
D    False
E    False
Name: Y, dtype: bool

For two conditions you can use | and & with parenthesis:

In [159]:
df[(df['W']>0) & (df['Y'] > 1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [160]:
df[(df['W']>0) | (df['Y'] > 1)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [161]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [162]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [163]:
newind = 'CA NY WY OR CO'.split()

In [164]:
df['States'] = newind

In [165]:
df

          W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NY
C  0.807706  0.072960  0.638787  0.329646     WY
D -0.497104 -0.754070 -0.943406  0.484752     OR
E -0.116773  1.901755  0.238127  1.996652     CO

In [166]:
df.set_index('States')

               W         X         Y         Z
States
CA      0.302665  1.693723 -1.706086 -1.159119
NY     -0.134841  0.390528  0.166905  0.184502
WY      0.807706  0.072960  0.638787  0.329646
OR     -0.497104 -0.754070 -0.943406  0.484752
CO     -0.116773  1.901755  0.238127  1.996652

In [167]:
df

          W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NY
C  0.807706  0.072960  0.638787  0.329646     WY
D -0.497104 -0.754070 -0.943406  0.484752     OR
E -0.116773  1.901755  0.238127  1.996652     CO

In [168]:
df.set_index('States',inplace=True)

In [169]:
df

               W         X         Y         Z
States
CA      0.302665  1.693723 -1.706086 -1.159119
NY     -0.134841  0.390528  0.166905  0.184502
WY      0.807706  0.072960  0.638787  0.329646
OR     -0.497104 -0.754070 -0.943406  0.484752
CO     -0.116773  1.901755  0.238127  1.996652

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [182]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [181]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [183]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [184]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.147027 -0.479448
   2  0.558769  1.024810
   3 -0.925874  1.862864
G2 1 -1.133817  0.610478
   2  0.386030  2.084019
   3 -0.376519  0.230336

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [186]:
df.loc['G1']

          A         B
1  0.147027 -0.479448
2  0.558769  1.024810
3 -0.925874  1.862864

In [187]:
df.loc['G1'].loc[1]

A    0.147027
B   -0.479448
Name: 1, dtype: float64

In [188]:
df.index.names

FrozenList([None, None])

In [189]:
df.index.names = ['Group','Num']

In [190]:
df

                  A         B
Group Num
G1    1    0.147027 -0.479448
      2    0.558769  1.024810
      3   -0.925874  1.862864
G2    1   -1.133817  0.610478
      2    0.386030  2.084019
      3   -0.376519  0.230336

In [193]:
df.loc["G1"].loc[2]["B"]

np.float64(1.0248102783372157)

## Crossection

In [194]:
df.xs('G1')

            A         B
Num
1    0.147027 -0.479448
2    0.558769  1.024810
3   -0.925874  1.862864

In [196]:
df.xs(1,level="Num")

              A         B
Group
G1     0.147027 -0.479448
G2    -1.133817  0.610478

In [199]:
df.xs(1,level='Num')

              A         B
Group
G1     0.147027 -0.479448
G2    -1.133817  0.610478

# Great Job!