___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [3]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [4]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [5]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [16]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [36]:
df2 = pd.DataFrame(np.random.randn(10,10),index=["A","B","C","D","E","F","G","H","I","J"],columns=["One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten"])
df2

,One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten
A,1.675553,0.856614,-1.200844,-0.084446,-0.408429,-0.546192,0.497752,-0.730370,-0.273170,-1.491513
B,0.680979,0.593531,-0.486841,0.012243,-0.236515,-1.200625,0.998088,1.132354,0.623840,-0.439931
C,1.901830,1.429653,-0.825605,-0.280709,0.228564,-0.798877,0.661290,0.926166,-0.952806,0.595269
D,-0.036241,0.716483,-0.486462,-0.139522,-1.881390,-0.061841,0.081210,0.207241,0.322675,-1.167838
E,1.322381,-2.986419,1.794662,-0.043704,-0.146561,0.321678,-0.909048,-0.644487,-1.444612,0.651572
F,-0.615908,0.618822,1.042220,-0.207740,0.815431,-1.724652,0.200112,-1.665389,-0.498706,0.938612
G,-0.917852,-0.190952,-0.241636,-0.619112,-0.866562,1.803931,0.587945,-0.180209,0.671996,0.378197
H,2.415966,-1.507797,-0.232226,0.042667,0.149056,-1.041381,1.504541,0.434465,0.335159,0.373734
I,-1.484976,-0.686328,-1.534736,-0.742847,0.489168,-0.261827,-0.870549,-0.897482,0.512470,-0.099257
J,-0.024986,-0.393920,0.089018,-0.368364,0.668578,1.918885,-0.300846,2.311621,-0.057192,-0.636851

In [37]:

df2 = df2[df2>0]
df2

,One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten
A,1.675553,0.856614,NaN,NaN,NaN,NaN,0.497752,NaN,NaN,NaN
B,0.680979,0.593531,NaN,0.012243,NaN,NaN,0.998088,1.132354,0.623840,NaN
C,1.901830,1.429653,NaN,NaN,0.228564,NaN,0.661290,0.926166,NaN,0.595269
D,NaN,0.716483,NaN,NaN,NaN,NaN,0.081210,0.207241,0.322675,NaN
E,1.322381,NaN,1.794662,NaN,NaN,0.321678,NaN,NaN,NaN,0.651572
F,NaN,0.618822,1.042220,NaN,0.815431,NaN,0.200112,NaN,NaN,0.938612
G,NaN,NaN,NaN,NaN,NaN,1.803931,0.587945,NaN,0.671996,0.378197
H,2.415966,NaN,NaN,0.042667,0.149056,NaN,1.504541,0.434465,0.335159,0.373734
I,NaN,NaN,NaN,NaN,0.489168,NaN,NaN,NaN,0.512470,NaN
J,NaN,NaN,0.089018,NaN,0.668578,1.918885,NaN,2.311621,NaN,NaN

In [38]:
df2.fillna(value="Fix")

,One,Two,Three,Four,Five,Six,Seven,Eight,Nine,Ten
A,1.675553,0.856614,Fix,Fix,Fix,Fix,0.497752,Fix,Fix,Fix
B,0.680979,0.593531,Fix,0.012243,Fix,Fix,0.998088,1.132354,0.62384,Fix
C,1.90183,1.429653,Fix,Fix,0.228564,Fix,0.66129,0.926166,Fix,0.595269
D,Fix,0.716483,Fix,Fix,Fix,Fix,0.08121,0.207241,0.322675,Fix
E,1.322381,Fix,1.794662,Fix,Fix,0.321678,Fix,Fix,Fix,0.651572
F,Fix,0.618822,1.04222,Fix,0.815431,Fix,0.200112,Fix,Fix,0.938612
G,Fix,Fix,Fix,Fix,Fix,1.803931,0.587945,Fix,0.671996,0.378197
H,2.415966,Fix,Fix,0.042667,0.149056,Fix,1.504541,0.434465,0.335159,0.373734
I,Fix,Fix,Fix,Fix,0.489168,Fix,Fix,Fix,0.51247,Fix
J,Fix,Fix,0.089018,Fix,0.668578,1.918885,Fix,2.311621,Fix,Fix

In [40]:
df2["One"].fillna(value=df2["One"].mean())

A    1.675553
B    0.680979
C    1.901830
D    1.599342
E    1.322381
F    1.599342
G    1.599342
H    2.415966
I    1.599342
J    1.599342
Name: One, dtype: float64

In [7]:
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [8]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Great Job!